### PR TITLE
Adds Header Allow/Deny Policy.

### PR DESCRIPTION
**Pull request by outofcoffee**
A policy that permits or denies requests matching certain HTTP headers.

The policy allows the user to control which incoming requests are permitted to be passed on to the back-end service. Permission is granted by adding entries for a header.

## How it works

On receiving a request, the policy examines the HTTP headers, then applies the configured rules using a regular expression against the names and values. If these are permitted, the request is passed to the back-end API unmodified. If not, an HTTP 403 response is returned and the call to the back-end service is not made.

## Examples

Plugin added:

Screenshot 2020-04-21 at 10 56 04

Example header configuration:

Screenshot 2020-04-21 at 11 08 15

Successful request:

```
curl -vk https://localhost:8443/apiman-gateway/test/example/1.0 -H 'Host: secret-domain.com'
...
> GET /apiman-gateway/test/example/1.0 HTTP/1.1
> Host: secret-domain.com
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 200
< Server: ECS (nyb/1D2A)
< Date: Tue, 21 Apr 2020 10:21:13 GMT
< Last-Modified: Thu, 17 Oct 2019 07:18:26 GMT
< Accept-Ranges: bytes
< Vary: Accept-Encoding
< Expires: Tue, 28 Apr 2020 10:21:13 GMT
< Age: 414817
< Etag: "3147526947+ident"
< X-Cache: HIT
< Cache-Control: max-age=604800
< Content-Type: text/html;charset=UTF-8
< Transfer-Encoding: chunked
<
<!doctype html>
<html>
...
```

Denied request:

```
curl -vk https://localhost:8443/apiman-gateway/test/example/1.0
...
> GET /apiman-gateway/test/example/1.0 HTTP/1.1
> Host: localhost:8443
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 403
< X-Policy-Failure-Type: Authorization
< X-Policy-Failure-Message: Request not permitted as no rules matched.
< X-Policy-Failure-Code: 403
< Content-Type: application/json
< Transfer-Encoding: chunked
< Date: Tue, 21 Apr 2020 10:20:25 GMT
<
* Connection #0 to host localhost left intact
{"type":"Authorization","failureCode":403,"responseCode":0,"message":"Request not permitted as no rules matched.","headers":{}}* Closing connection 0
```

### CODE REVIEW

**Comment by EricWittmann** [comment]
Nice policy.  Thanks!  Get some more coffee.

**Comment by volkflo** [comment]
@outofcoffee This looks like a very cool policy 👍

**Comment by volkflo** [comment]
@EricWittmann and @outofcoffee Can we add this policy into the registry?
https://github.com/apiman/apiman-plugin-registry/blob/master/registry.json
Not sure if this counts as "official apiman plugin"

The problem for me is that the button here is not working (I didn't checked why yet):
image

**Comment by msavy** [comment]
Looks like a good candidate for adding to the list, IMO.

**Comment by EricWittmann** [comment]
+1

**Comment by EricWittmann** [comment]
@outofcoffee can you submit a PR to update the registry with your new plugin?

**Comment by pcornish** [comment]
Will do @EricWittmann @msavy. I also need to add this to the Maven `modules` list here in the root POM. Skipped it in the rebase (sorry!)

**Comment by outofcoffee** [comment]
Done:

* Maven module: #98 
* Registry: https://github.com/apiman/apiman-plugin-registry/pull/3

**Pull request merged**
