### PR TITLE
test(http-security-policy) Add test to cover basic usage.

### PR DESCRIPTION
**Pull request by msavy**

### CODE REVIEW

**Comment by EricWittmann** [comment]
Travis failure for this PR?

**Comment by msavy** [comment]
It relies upon apiman/apiman fa6f29 - which isn’t present in the latest deployed 1.2.6-SNAPSHOT, I believe. 

I’m not sure if you finally managed to deploy 1.2.6.Beta1 successfully after those crashes?

Another snapshot release of apiman/apiman should fix it, I reckon. Works locally, anyway.

**Comment by EricWittmann** [comment]
OK cool thanks.  Still working on the release.  I'll try to get a new snapshot release done as well.  Did you tell me about that?

**Comment by msavy** [comment]
> Did you tell me about that?

Only did this PR yesterday (Saturday), and hadn’t realised there wasn’t an up-to-date snapshot until I saw your email this afternoon. 

No big rush from my end!

**Pull request merged**
