### PR TITLE
APIMAN-897 Adding a simple log policy

### PR DESCRIPTION
**Pull request by tonswieb**
Hi,

As a first attempt for https://issues.jboss.org/browse/APIMAN-897 I create a very simple log policy for the 1.1.x branch.
Could you add it to the main project? It would make it a lot easier to use the plugin from within apiman.
Thanks.

Regards,

Ton

### CODE REVIEW

**Comment by EricWittmann** [comment]
Nice, thanks.

We should add a json schema to this for configuration, along with adding a configuration option for which direction (request, response, both) should be logged.

**Comment by EricWittmann** [comment]
@tonswieb - Note: I have migrated this policy to the master branch.  In addition, I added a configuration schema along with an option to choose whether you want to log headers from the Request, the Response, or Both.  Have a look:

https://github.com/apiman/apiman-plugins/blob/master/log-policy/src/main/apiman/policyDefs/schemas/log-policyDef.schema

**Comment by tonswieb** [comment]
Thanks for merging to master and adding the policy. Looks great! I will take it for a test drive.
Is there a particular reason why logging frameworks are not used within Apiman plugins, but instead stdout is used? Or perhaps they are used, but I haven't run into them yet?

**Comment by EricWittmann** [comment]
It's something that's been a low priority task on the to-do list for awhile now.  Here is an older JIRA to add a logging component that can be used by policies:

https://issues.jboss.org/browse/APIMAN-586

It needs to be addressed at some point, but we just haven't gotten to it yet.

**Pull request merged**
