### PR TITLE
TimeOut-Policy : new policy creation

### PR DESCRIPTION
**Pull request by wbeck-fr**
Proposition for a policy which manage timeout http client connection to the back-end api.
Response for the [https://github.com/apiman/apiman/issues/851](https://github.com/apiman/apiman/issues/851)

### CODE REVIEW

**Review by bekihm — APPROVED** [review]
LGTM

Do we need also a policy form for this?
https://github.com/apiman/apiman/tree/39d96922fbe125243b4390e27e174f7d4e695bb6/manager/ui/war/plugins/api-manager/html/policyForms

**Comment by wbeck-fr** [comment]
Hello,
Thanks for the approval. I don't think a policy form was necessary because I have include a policyDef.schema inside.
Best regards

**Comment by volkflo** [comment]
@wbeck-fr Thanks for the contribution :) Is this also working for the vert.x gateway implementation?

**Comment by wbeck-fr** [comment]
@volkflo Yes, it's working for Vertx and servlet gateway  implementation.

**Pull request merged**
